-- MySQL Script generated by MySQL Workbench
-- Tue May  3 08:17:50 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tblUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblUser` (
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `id` INT NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`LkupCoin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LkupCoin` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `ticker` VARCHAR(45) NOT NULL,
  `isToken` TINYINT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`LkUpExchange`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LkUpExchange` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `url` VARCHAR(45) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`LkUpFx`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LkUpFx` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `ticker` VARCHAR(45) NULL,
  `hourlyValue` DECIMAL(4) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`tblTx`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblTx` (
  `id` INT NOT NULL,
  `buyCoinId` INT NOT NULL,
  `sellCoinId` INT NOT NULL,
  `dateTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `userId` INT NOT NULL,
  `buyCoinPrice` DECIMAL(4) NOT NULL,
  `sellCoinPrice` DECIMAL(4) NOT NULL,
  `buyUnits` DECIMAL(4) NOT NULL,
  `sellUnits` DECIMAL(4) NOT NULL,
  `exchangeId` INT NOT NULL,
  `notes` VARCHAR(45) NULL,
  `fxId` INT NULL,
  `fxRate` DECIMAL(4) NULL,
  `fees` DECIMAL(4) NULL,
  PRIMARY KEY (`id`),
  INDEX `userId` (`userId` ASC) VISIBLE,
  INDEX `buyCoinId_idx` (`buyCoinId` ASC) VISIBLE,
  INDEX `sellCoinId_idx` (`sellCoinId` ASC) VISIBLE,
  INDEX `exchangeId_idx` (`exchangeId` ASC) VISIBLE,
  INDEX `fxId_idx` (`fxId` ASC) VISIBLE,
  CONSTRAINT `userId`
    FOREIGN KEY (`userId`)
    REFERENCES `mydb`.`tblUser` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `buyCoinId`
    FOREIGN KEY (`buyCoinId`)
    REFERENCES `mydb`.`LkupCoin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sellCoinId`
    FOREIGN KEY (`sellCoinId`)
    REFERENCES `mydb`.`LkupCoin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `exchangeId`
    FOREIGN KEY (`exchangeId`)
    REFERENCES `mydb`.`LkUpExchange` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fxId`
    FOREIGN KEY (`fxId`)
    REFERENCES `mydb`.`LkUpFx` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`tblPortfolio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblPortfolio` (
  `id` INT NOT NULL,
  `userId` INT NOT NULL,
  `coinId` INT NOT NULL,
  `firstTxDate` DATETIME NOT NULL,
  `lastTxDate` DATETIME NOT NULL,
  `units` DECIMAL(4) NOT NULL,
  `avgCost` DECIMAL(4) NOT NULL,
  `numBuyTx` INT NOT NULL,
  `numSellTx` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `userId_idx` (`userId` ASC) VISIBLE,
  INDEX `coinId_idx` (`coinId` ASC) VISIBLE,
  CONSTRAINT `userId`
    FOREIGN KEY (`userId`)
    REFERENCES `mydb`.`tblUser` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `coinId`
    FOREIGN KEY (`coinId`)
    REFERENCES `mydb`.`LkupCoin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`tblWallets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblWallets` (
  `id` INT NOT NULL,
  `userId` INT NOT NULL,
  `exchangeId` INT NOT NULL,
  `coinId` INT NOT NULL,
  `isToken` TINYINT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `units` DECIMAL(4) NOT NULL,
  `staked` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `userId_idx` (`userId` ASC) VISIBLE,
  INDEX `exchangeId_idx` (`exchangeId` ASC) VISIBLE,
  INDEX `coinId_idx` (`coinId` ASC) VISIBLE,
  CONSTRAINT `userId`
    FOREIGN KEY (`userId`)
    REFERENCES `mydb`.`tblUser` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `exchangeId`
    FOREIGN KEY (`exchangeId`)
    REFERENCES `mydb`.`LkUpExchange` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `coinId`
    FOREIGN KEY (`coinId`)
    REFERENCES `mydb`.`LkupCoin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
