-- MySQL Script generated by MySQL Workbench
-- Mon Mar 28 13:52:45 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `id` INT NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `locationsLkUp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locationsLkUp` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `street` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `categoryLkUp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `categoryLkUp` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `vendorLkUp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendorLkUp` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`));

-- -----------------------------------------------------
-- Table `modelNumLkUp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelNumLkUp` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `categoryId` INT NULL,
  `vendorId` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `categoryId`
    FOREIGN KEY (`categoryId`)
    REFERENCES `categoryLkUp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `vendorId`
    FOREIGN KEY (`vendorId`)
    REFERENCES `vendorLkUp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

-- -----------------------------------------------------
-- Table `roomLkUp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roomLkUp` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `locationId` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `locationId`
    FOREIGN KEY (`locationId`)
    REFERENCES `locationsLkUp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `shelfLkUp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shelfLkUp` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `roomId` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `roomId`
    FOREIGN KEY (`roomId`)
    REFERENCES `roomLkUp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

-- -----------------------------------------------------
-- Table `items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `items` (
  `id` INT NOT NULL,
  `poNumber` VARCHAR(45) NULL,
  `serialNumber` VARCHAR(45) NOT NULL,
  `isPart` TINYINT NOT NULL,
  `rcvdDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `shelfId` INT NULL,
  `categoryId` INT NULL,
  `modelId` INT NULL,
  `rcvdBy` INT NULL,
  `vendorId` INT NULL,
  `roomId` INT NULL,
  `locationId` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `shelfId`
    FOREIGN KEY (`shelfId`)
    REFERENCES `shelfLkUp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `vendorId`
    FOREIGN KEY (`vendorId`)
    REFERENCES `vendorLkUp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rcvdBy`
    FOREIGN KEY (`rcvdBy`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `modelId`
    FOREIGN KEY (`modelId`)
    REFERENCES `modelNumLkUp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `roomId`
    FOREIGN KEY (`roomId`)
    REFERENCES `roomLkUp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `locationId`
    FOREIGN KEY (`locationId`)
    REFERENCES `locationsLkUp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `categoryId`
    FOREIGN KEY (`categoryId`)
    REFERENCES `categoryLkUp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `partQuantity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `partQuantity` (
  `count` INT NOT NULL,
  `itemId` INT NULL,
  CONSTRAINT `itemId`
    FOREIGN KEY (`itemId`)
    REFERENCES `items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
